version: "3"

services:
  unbound:
    image: mvance/unbound:latest
    container_name: unbound
    restart: unless-stopped
    ports:
      - "5335:53/udp"
      - "5335:53/tcp"
    volumes:
      - ./etc-unbound/unbound.conf:/etc/unbound/unbound.conf
      - ./etc-unbound/root.key:/var/lib/unbound/root.key
    networks:
      - dns_net

  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    restart: unless-stopped
    hostname: pihole
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80"
    environment:
      TZ: 'Asia/Seoul'
      WEBPASSWORD: 'q1w2e3R$'
      DNS1: 127.0.0.1#5335   # Unbound 컨테이너로 포워딩
      DNS2: 127.0.0.1#5335
    volumes:
      - ./etc-pihole:/etc/pihole
      - ./etc-dnsmasq.d:/etc/dnsmasq.d
    depends_on:
      - unbound
    networks:
      - dns_net
    cap_add:
      - NET_ADMIN

networks:
  dns_net:
    driver: bridge
